name: Trigger auto deployment for container-app-nybgl5muap4wm

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-nybgl5muap4wm-AutoDeployTrigger-2a70720a-e6fc-4124-a91b-169bc5f3876d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPNYBGL5MUAP4WM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPNYBGL5MUAP4WM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPNYBGL5MUAP4WM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPNYBGL5MUAP4WM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPNYBGL5MUAP4WM_REGISTRY_PASSWORD }}
          containerAppName: container-app-nybgl5muap4wm
          resourceGroup: ehtodoappbb01
          imageToBuild: default/container-app-nybgl5muap4wm:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


